/** Role 1 public boundary for platform and capture adapters. */
export {
  audienceEventSchema,
  gameplayFrameObservationSchema,
  platformEventSchema,
} from "../core";
export type {
  AudienceEvent,
  AudienceEventSource,
  EphemeralGameplayFrame,
  FrameSource,
  GameplayFrameObservation,
  PlatformEvent,
} from "../core";
export {
  FixedWindowTwitchChatRateLimiter,
  deliverTwitchChatFallbackAnnouncement,
  deliverTwitchChatVoteAcknowledgement,
  deliverTwitchChatVoteSubmissionAcknowledgement,
  type DeliveredTwitchChatVoteAcknowledgement,
  type DeliveredTwitchChatVoteSubmissionAcknowledgement,
  type DeliverTwitchChatFallbackAnnouncementInput,
  type DeliverTwitchChatVoteAcknowledgementInput,
  type DeliverTwitchChatVoteSubmissionAcknowledgementInput,
  type TwitchChatOutboundAttempt,
  type TwitchChatOutboundMessage,
  type TwitchChatOutboundSender,
  type TwitchChatRateLimitDecision,
  type TwitchChatRateLimiter,
} from "./twitch/chat-delivery";
export {
  handleTwitchChatVoteMessage,
  type TwitchChatVoteMessageHandlerDependencies,
  type TwitchChatVoteMessageHandlingResult,
} from "./twitch/chat-handler";
export {
  TwitchChatVerifiedVoteActorStore,
  normaliseTwitchChatVote,
  submitTwitchChatVote,
  twitchChatVoteAcknowledgementIntent,
  twitchChatActorId,
  twitchChatVoterKey,
  type TwitchChatVoteAcknowledgementIntent,
  type TwitchChatVoteExecutor,
  type TwitchChatVerifiedVoteActor,
  type TwitchChatVoteMessage,
  type TwitchChatVoteNormalisationResult,
  type TwitchChatVoteSubmissionDependencies,
  type TwitchChatVoteSubmissionResult,
} from "./twitch/chat-votes";
export {
  TWITCH_EXTENSION_CONFIG_PATH,
  TWITCH_EXTENSION_LIVE_CONFIG_PATH,
  TWITCH_EXTENSION_PANEL_HEIGHT_PX,
  TWITCH_EXTENSION_VIEWER_PATH,
  TWITCH_EXTENSION_VIEW_DECISION_ID,
  TWITCH_LOCAL_CALLBACK_URL,
  TWITCH_OAUTH_CALLBACK_PATH,
  TWITCH_REGISTRATION_DECISION_ID,
  resolveTwitchSetupRegistrationManifest,
  resolveTwitchSetupReadiness,
  type TwitchSetupRegistrationManifest,
  type TwitchSetupReadiness,
} from "./twitch/setup";
export {
  OBS_CAPTURE_LIFECYCLE_DECISION_ID,
  OBS_CAPTURE_MAX_STALE_FRAME_MS,
  OBS_CAPTURE_MIN_HEIGHT,
  OBS_CAPTURE_MIN_WIDTH,
  OBS_CAPTURE_SAMPLE_INTERVAL_MS,
  OBS_CAPTURE_TARGET_SOURCE_KIND,
  obsCaptureBrowserReportSchema,
  obsCaptureLifecycleStatusSchema,
  obsCapturePermissionStateSchema,
  obsCaptureSelectedSourceKindSchema,
  obsCaptureSetupResolutionSchema,
  resolveObsCaptureSetup,
  type ObsCaptureBrowserReport,
  type ObsCaptureLifecycleStatus,
  type ObsCapturePermissionState,
  type ObsCaptureSelectedSourceKind,
  type ObsCaptureSetupResolution,
} from "./obs/capture-session";
export {
  MAX_OBS_OVERLAY_READ_GRANT_MILLISECONDS,
  buildObsOverlaySnapshotUrl,
  issueObsOverlayReadGrant,
  readObsOverlaySnapshot,
  type ObsOverlayReadGrantDependencies,
  type ObsOverlayReadGrantInput,
  type ObsOverlayReadGrantResult,
  type ObsOverlaySnapshotReadDependencies,
  type ObsOverlaySnapshotReadInput,
  type ObsOverlaySnapshotReadResult,
} from "./obs/overlay-snapshot";
