/** Role 1 public boundary for platform and capture adapters. */
export {
  audienceEventSchema,
  gameplayFrameObservationSchema,
  platformEventSchema,
} from "../core";
export type {
  AudienceEvent,
  AudienceEventSource,
  EphemeralGameplayFrame,
  FrameSource,
  GameplayFrameObservation,
  PlatformEvent,
} from "../core";
export {
  FALLBACK_DELIVERY_DECISION_ID,
  fallbackDeliveryPolicyReportSchema,
  fallbackDeliveryPolicyResolutionSchema,
  fallbackDeliveryVerificationSchema,
  resolveFallbackDeliveryPolicy,
  type FallbackDeliveryPolicyReport,
  type FallbackDeliveryPolicyResolution,
  type FallbackDeliveryVerification,
} from "./test-lab/fallback-delivery-policy";
export {
  PRIVATE_VIEWER_RECOVERY_DECISION_ID,
  privateViewerRecoveryPolicyReportSchema,
  privateViewerRecoveryPolicyResolutionSchema,
  privateViewerRecoveryVerificationSchema,
  resolvePrivateViewerRecoveryPolicy,
  type PrivateViewerRecoveryPolicyReport,
  type PrivateViewerRecoveryPolicyResolution,
  type PrivateViewerRecoveryVerification,
} from "./test-lab/private-viewer-recovery-policy";
export {
  UI_GATEWAY_HARNESS_DECISION_ID,
  resolveUiGatewayHarnessPolicy,
  uiGatewayHarnessPolicyReportSchema,
  uiGatewayHarnessPolicyResolutionSchema,
  uiGatewayHarnessSurfaceSchema,
  uiGatewayHarnessVerificationSchema,
  type UiGatewayHarnessPolicyReport,
  type UiGatewayHarnessPolicyResolution,
  type UiGatewayHarnessSurface,
  type UiGatewayHarnessVerification,
} from "./test-lab/ui-gateway-harness-policy";
export {
  MINIMUM_REAL_WORKFLOW_EVIDENCE_DECISION_ID,
  minimumRealWorkflowEvidenceReportSchema,
  minimumRealWorkflowEvidenceResolutionSchema,
  realWorkflowEvidenceClassSchema,
  realWorkflowParticipationModeSchema,
  realWorkflowSurfaceSchema,
  realWorkflowTerminalOutcomeSchema,
  resolveMinimumRealWorkflowEvidence,
  type MinimumRealWorkflowEvidenceReport,
  type MinimumRealWorkflowEvidenceResolution,
  type RealWorkflowEvidenceClass,
  type RealWorkflowParticipationMode,
  type RealWorkflowSurface,
  type RealWorkflowTerminalOutcome,
} from "./test-lab/minimum-real-workflow-evidence";
export {
  CONTROLLED_GAMEPLAY_TEST_DECISION_ID,
  controlledGameplayEvidenceResourceSchema,
  controlledGameplayOwnershipSchema,
  controlledGameplayRunModeSchema,
  controlledGameplayRunReportSchema,
  controlledGameplayScenarioSchema,
  controlledGameplayTestPlanSchema,
  controlledGameplayTestResolutionSchema,
  resolveControlledGameplayTestPlan,
  type ControlledGameplayEvidenceResource,
  type ControlledGameplayOwnership,
  type ControlledGameplayRunMode,
  type ControlledGameplayRunReport,
  type ControlledGameplayScenario,
  type ControlledGameplayTestPlan,
  type ControlledGameplayTestResolution,
} from "./test-lab/controlled-gameplay";
export {
  FixedWindowTwitchChatRateLimiter,
  deliverTwitchChatFallbackAnnouncement,
  deliverTwitchChatVoteAcknowledgement,
  deliverTwitchChatVoteSubmissionAcknowledgement,
  type DeliveredTwitchChatVoteAcknowledgement,
  type DeliveredTwitchChatVoteSubmissionAcknowledgement,
  type DeliverTwitchChatFallbackAnnouncementInput,
  type DeliverTwitchChatVoteAcknowledgementInput,
  type DeliverTwitchChatVoteSubmissionAcknowledgementInput,
  type TwitchChatOutboundAttempt,
  type TwitchChatOutboundMessage,
  type TwitchChatOutboundSender,
  type TwitchChatRateLimitDecision,
  type TwitchChatRateLimiter,
} from "./twitch/chat-delivery";
export {
  handleTwitchChatVoteMessage,
  type TwitchChatVoteMessageHandlerDependencies,
  type TwitchChatVoteMessageHandlingResult,
} from "./twitch/chat-handler";
export {
  TwitchChatVerifiedVoteActorStore,
  normaliseTwitchChatVote,
  submitTwitchChatVote,
  twitchChatVoteAcknowledgementIntent,
  twitchChatActorId,
  twitchChatVoterKey,
  type TwitchChatVoteAcknowledgementIntent,
  type TwitchChatVoteExecutor,
  type TwitchChatVerifiedVoteActor,
  type TwitchChatVoteMessage,
  type TwitchChatVoteNormalisationResult,
  type TwitchChatVoteSubmissionDependencies,
  type TwitchChatVoteSubmissionResult,
} from "./twitch/chat-votes";
export {
  TWITCH_EXTENSION_CONFIG_PATH,
  TWITCH_EXTENSION_LIVE_CONFIG_PATH,
  TWITCH_EXTENSION_PANEL_HEIGHT_PX,
  TWITCH_EXTENSION_VIEWER_PATH,
  TWITCH_EXTENSION_VIEW_DECISION_ID,
  TWITCH_LOCAL_CALLBACK_URL,
  TWITCH_OAUTH_CALLBACK_PATH,
  TWITCH_REGISTRATION_DECISION_ID,
  resolveTwitchSetupRegistrationManifest,
  resolveTwitchSetupReadiness,
  type TwitchSetupRegistrationManifest,
  type TwitchSetupReadiness,
} from "./twitch/setup";
export {
  OBS_CAPTURE_LIFECYCLE_DECISION_ID,
  OBS_CAPTURE_MAX_STALE_FRAME_MS,
  OBS_CAPTURE_MIN_HEIGHT,
  OBS_CAPTURE_MIN_WIDTH,
  OBS_CAPTURE_SAMPLE_INTERVAL_MS,
  OBS_CAPTURE_TARGET_SOURCE_KIND,
  obsCaptureBrowserReportSchema,
  obsCaptureLifecycleStatusSchema,
  obsCapturePermissionStateSchema,
  obsCaptureSelectedSourceKindSchema,
  obsCaptureSetupResolutionSchema,
  resolveObsCaptureSetup,
  type ObsCaptureBrowserReport,
  type ObsCaptureLifecycleStatus,
  type ObsCapturePermissionState,
  type ObsCaptureSelectedSourceKind,
  type ObsCaptureSetupResolution,
} from "./obs/capture-session";
export {
  MAX_OBS_OVERLAY_READ_GRANT_MILLISECONDS,
  buildObsOverlaySnapshotUrl,
  issueObsOverlayReadGrant,
  readObsOverlaySnapshot,
  type ObsOverlayReadGrantDependencies,
  type ObsOverlayReadGrantInput,
  type ObsOverlayReadGrantResult,
  type ObsOverlaySnapshotReadDependencies,
  type ObsOverlaySnapshotReadInput,
  type ObsOverlaySnapshotReadResult,
} from "./obs/overlay-snapshot";
